[theme]
base = "dark"
primaryColor = "#6366f1"
backgroundColor = "#0f172a"
secondaryBackgroundColor = "#1e293b"
textColor = "#f1f5f9"
font = "sans serif"

[server]
maxUploadSize = 200
enableCORS = true
enableXsrfProtection = false

[browser]
serverAddress = "localhost"
gatherUsageStats = false
serverPort = 8501